// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSimulationSpeed():Promise<number>;

export function GetSimulationState():Promise<main.SimulationState>;

export function SetSimulationSpeed(arg1:number):Promise<void>;
