// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSimulationSpeed() {
  return window['go']['main']['App']['GetSimulationSpeed']();
}

export function GetSimulationState() {
  return window['go']['main']['App']['GetSimulationState']();
}

export function SetSimulationSpeed(arg1) {
  return window['go']['main']['App']['SetSimulationSpeed'](arg1);
}
